# Python code generated by AutomateBard.com

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

COOKIE_NAME = "__Secure-1PSID"
COOKIE_VALUE = "<paste cookie value here>"


def search_bard(web_driver, search_string):
    search_bar = web_driver.find_element("id", "mat-input-0")
    search_bar.clear()

    # Enter Search String
    search_bar.send_keys(search_string)

    # Submit Search
    search_bar.send_keys(Keys.ENTER)

    # Allow time for Bard to respond
    time.sleep(10.0)

    # Grab response and return
    return web_driver.find_element(By.CLASS_NAME, "model-response-text").text


# Main Script
if __name__ == '__main__':

    try:
        print("Connecting to ChromeDriver")
        driver = webdriver.Chrome('./chromedriver')
        driver.implicitly_wait(1.0)

        print("Connecting to dummy site")
        driver.get("https://bard.google.com/u/1/")

        print("Adding cookie")
        driver.add_cookie({
            "name": COOKIE_NAME,
            "value": COOKIE_VALUE
        })

        print("Transferring to Bard site")
        driver.get("https://bard.google.com/u/1/")

        response = search_bard(driver, "How are you, today?")
        print("Bard Replied:", response)

    except Exception as e:
        # DO NOT DO THIS. Use proper exception handling!
        print(e)

    finally:
        print("Closing ChromeDriver")
        driver.close()