# Python code generated by AutomateBard.com

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

from configparser import ConfigParser
config_object = ConfigParser()
config_object.read("./config.txt")

# create your own config.txt file (containing user sensitive info) with the following format:
# [USERINFO]
# COOKIE_VALUE = "YOUR COOKIE VALUE HERE"
# any_other_value = "any other value here"
# etc.

COOKIE_NAME = "__Secure-1PSID"
COOKIE_VALUE = config_object["USERINFO"]['COOKIE_VALUE']


def search_bard(web_driver, search_string):
    search_bar = web_driver.find_element("id", "mat-input-0")
    search_bar.clear()

    # Enter Search String
    search_bar.send_keys(search_string)

    # Submit Search
    search_bar.send_keys(Keys.ENTER)

    # Allow time for Bard to respond
    time.sleep(10.0)

    # Grab response and return
    return web_driver.find_element(By.CLASS_NAME, "model-response-text").text


# Main Script
if __name__ == '__main__':

    try:
        print("Connecting to ChromeDriver")
        driver = webdriver.Chrome()
        driver.implicitly_wait(1.0)

        print("Connecting to dummy site")
        driver.get("https://bard.google.com/u/1/")

        print("Adding cookie")
        driver.add_cookie({
            "name": COOKIE_NAME,
            "value": COOKIE_VALUE,
            "domain": ".google.com",
            "path": "/",
            "secure": True,
            "httpOnly": True
        })

        print("Transferring to Bard site")
        driver.get("https://bard.google.com/u/1/")

        response = search_bard(driver, "How are you, today?")
        print("Bard Replied:", response)

    except Exception as e:
        # DO NOT DO THIS. Use proper exception handling!
        print(e)

    finally:
        print("Closing ChromeDriver")
        driver.close()